version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: yy
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
